-- MySQL Script generated by MySQL Workbench
-- 04/01/16 22:33:40
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sistema_prestamos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistema_prestamos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistema_prestamos` DEFAULT CHARACTER SET utf8 ;
USE `sistema_prestamos` ;

-- -----------------------------------------------------
-- Table `sistema_prestamos`.`Aula`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_prestamos`.`Aula` ;

CREATE TABLE IF NOT EXISTS `sistema_prestamos`.`Aula` (
  `id_aula` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(45) NULL,
  `edificio` VARCHAR(45) NULL,
  `capacidad` VARCHAR(45) NULL,
  PRIMARY KEY (`id_aula`))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_prestamos`.`Rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_prestamos`.`Rol` ;

CREATE TABLE IF NOT EXISTS `sistema_prestamos`.`Rol` (
  `id_rol` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id_rol`))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_prestamos`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_prestamos`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `sistema_prestamos`.`Usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `rol_id` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_Usuarios_Rol1_idx` (`rol_id` ASC),
  CONSTRAINT `fk_Usuarios_Rol1`
  FOREIGN KEY (`rol_id`)
  REFERENCES `sistema_prestamos`.`Rol` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_prestamos`.`Dispositivo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_prestamos`.`Dispositivo` ;

CREATE TABLE IF NOT EXISTS `sistema_prestamos`.`Dispositivo` (
  `id_dispositivo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id_dispositivo`))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_prestamos`.`Prestamo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_prestamos`.`Prestamo` ;

CREATE TABLE IF NOT EXISTS `sistema_prestamos`.`Prestamo` (
  `id_prestamo` INT NOT NULL AUTO_INCREMENT,
  `hora_prestamo` TIME(6) NULL,
  `hora_devolucion` TIME(6) NULL,
  `idUsuario` INT NOT NULL,
  `dispositivo_id` INT NOT NULL,
  `aula_id` INT NOT NULL,
  PRIMARY KEY (`id_prestamo`),
  INDEX `fk_Prestamos_Usuarios1_idx` (`idUsuario` ASC),
  INDEX `fk_Prestamo_Dispositivo1_idx` (`dispositivo_id` ASC),
  INDEX `fk_Prestamo_Aula1_idx` (`aula_id` ASC),
  CONSTRAINT `fk_Prestamos_Usuarios1`
  FOREIGN KEY (`idUsuario`)
  REFERENCES `sistema_prestamos`.`Usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prestamo_Dispositivo1`
  FOREIGN KEY (`dispositivo_id`)
  REFERENCES `sistema_prestamos`.`Dispositivo` (`id_dispositivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prestamo_Aula1`
  FOREIGN KEY (`aula_id`)
  REFERENCES `sistema_prestamos`.`Aula` (`id_aula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_prestamos`.`Horario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_prestamos`.`Horario` ;

CREATE TABLE IF NOT EXISTS `sistema_prestamos`.`Horario` (
  `id_horario` INT NOT NULL AUTO_INCREMENT,
  `hora_entrada` TIME(6) NULL,
  `hora_salida` TIME(6) NULL,
  PRIMARY KEY (`id_horario`))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_prestamos`.`Aulas_has_Horario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_prestamos`.`Aulas_has_Horario` ;

CREATE TABLE IF NOT EXISTS `sistema_prestamos`.`Aulas_has_Horario` (
  `aula_id` INT NOT NULL,
  `horario_id` INT NOT NULL,
  PRIMARY KEY (`aula_id`, `horario_id`),
  INDEX `fk_Aulas_has_Horario_Horario1_idx` (`horario_id` ASC),
  INDEX `fk_Aulas_has_Horario_Aulas1_idx` (`aula_id` ASC),
  CONSTRAINT `fk_Aulas_has_Horario_Aulas1`
  FOREIGN KEY (`aula_id`)
  REFERENCES `sistema_prestamos`.`Aula` (`id_aula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aulas_has_Horario_Horario1`
  FOREIGN KEY (`horario_id`)
  REFERENCES `sistema_prestamos`.`Horario` (`id_horario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_prestamos`.`Equipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_prestamos`.`Equipo` ;

CREATE TABLE IF NOT EXISTS `sistema_prestamos`.`Equipo` (
  `id_equipo` INT NOT NULL,
  `nombre_equipo` VARCHAR(45) NULL,
  `aula_id` INT NOT NULL,
  PRIMARY KEY (`id_equipo`),
  INDEX `fk_Equipo_Aula1_idx` (`aula_id` ASC),
  CONSTRAINT `fk_Equipo_Aula1`
  FOREIGN KEY (`aula_id`)
  REFERENCES `sistema_prestamos`.`Aula` (`id_aula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
